### ISSUE TITLE
detect metadata inside archived files(cbz, zip, etc)?

### ISSUE THREAD

**Issue by andrizmitnick** [happypandax/plugins#31]
downloaded via hdoujin, cbz format, metadata in info.txt
the metadata can't be detected.
is it actually only support folder?
thanks before

**Comment by twiddli** [comment]
No, the files should be detected in archives too, but I think there's a bug (which I've fixed, just waiting for HPX v0.11) where it fails to detect the file if it's in a sub-folder inside the archive.

**Comment by andrizmitnick** [comment]
my cbz file are like this. there aren't any folder inside
comic-1.cbz
>info.txt
>01.jpg
>......

**Comment by twiddli** [comment]
What's the content of `info.txt`?  I can and replicate the issue on my end.

**Comment by andrizmitnick** [comment]
```
TITLE: Artist -  CuteSexyRobutts
ORIGINAL TITLE: 
AUTHOR: 
ARTIST: Cutesexyrobutts
CIRCLE: 
SCANLATOR: 
TRANSLATOR: 
PUBLISHER: 
DESCRIPTION: 
STATUS: 
CHAPTERS: N/A
PAGES: 656
TAGS: Artist:Cutesexyrobutts, Female:Dark Skin
TYPE: 
LANGUAGE: Japanese
RELEASED: 
READING DIRECTION: 
CHARACTERS: 
SERIES: 
PARODY: Final Fantasy Xiv, Nier Automata, Pokemon | Pocket Monsters, Street Fighter, The Legend Of Zelda, Xenosaga
URL: https://.......

```
like this one

**Comment by twiddli** [comment]
> if i extract the cbz, and add the folder to hpx library, all the information can be loaded. but if i add the cbz, the info aren't detected.

right, then I'm sure this issue is what I just fixed for the next HPX version.

**Comment by twiddli** [comment]
I believe this should now be fixed in `v0.11.0`, if not, then please re-open the issue

**Comment by andrizmitnick** [comment]
Hi, thank you so much for your works on the update.
i just tried it, but it's still doesn't work. 
it's always giving same error like before

> Sep-09 12:52:54--INFO   pluginctx.file-metadata.main: Attempting with DataType.hdoujin
Sep-09 12:52:54--INFO   pluginctx.file-metadata.main: DataType.hdoujin didn't match
Sep-09 12:52:54--INFO   pluginctx.file-metadata.main: Attempting with DataType.e_hentai_downloader
Sep-09 12:52:54--INFO   pluginctx.file-metadata.main: DataType.e_hentai_downloader didn't match

[here's one of the file](https://send.firefox.com/download/df70048063e42437/#dkuY4HcOzd3pns-2N7DebA) that i tried. i've been wondering if it's an issue within my own system or not. hope that's not the case 😄

**Comment by twiddli** [comment]
this should now be fixed in File Metadata `v2.0.1`
